name: Build container

on:
  push:
    branches:
      - "main"
    paths:
      - 'app/**'
      - 'Dockerfile'
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  container:
    name: Build container
    runs-on: ubuntu-22.04
    env:
      AWS_DEFAULT_REGION: us-east-2
      AWS_ROLE_SESSION_NAME: ${{ github.event.repository.name }}-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag, and push image to ECR and Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DOCKER_REGISTRY: jonknutson
          REPOSITORY: xyz-demo
          IMAGE_TAG: ${{ github.sha }}
        run : |
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$REPOSITORY:latest
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          docker tag $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker tag $DOCKER_REGISTRY/$REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$REPOSITORY:latest
          docker push $DOCKER_REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_REGISTRY/$REPOSITORY:latest
          echo "image=$DOCKER_REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT