name: Build container

on:
  push:
    branches:
      - "main"
    paths:
      - 'app/**'
      - 'Dockerfile'
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  container:
    name: Build container
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag, and push image to ECR and Docker Hub
        if: ( github.ref == 'refs/heads/main' && github.event_name == 'push' ) || github.event_name == 'workflow_dispatch'
        env:
          DOCKER_REGISTRY: jonknutson
          REPOSITORY: xyz-demo
          IMAGE_TAG: ${{ github.sha }}
        run : |
          docker build -t $DOCKER_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker tag $DOCKER_REGISTRY/$REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$REPOSITORY:latest
          docker push $DOCKER_REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_REGISTRY/$REPOSITORY:latest
          echo "image=$DOCKER_REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT