name: Container Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Tag Container Release
    runs-on: ubuntu-22.04

    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Fetch and tag image
        env:
          DOCKER_REGISTRY: jonknutson
          REPOSITORY: xyz-demo
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker pull $DOCKER_REGISTRY/$REPOSITORY:$GITHUB_SHA
          docker tag $DOCKER_REGISTRY/$REPOSITORY:$GITHUB_SHA $DOCKER_REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_REGISTRY/$REPOSITORY:$IMAGE_TAG