name: Remove Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./terraform
    env:
      AWS_DEFAULT_REGION: us-east-2
      AWS_ROLE_SESSION_NAME:  ${{ github.event.repository.name }}-terraform
      TF_IN_AUTOMATION: true
      TF_VAR_K8S_USER_ARN: ${{ secrets.K8S_USER_ARN }}
      TF_VAR_PIPELINE_ROLE: ${{ secrets.AWS_ROLE_ARN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}

      - name: Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Destroy
        run: terraform destroy -auto-approve